name: lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Dataverse UI Library
        working-directory: packages/design-system
        run: npm run build

      - name: Lint
        run: npm run lint
