name: test

on: push

jobs:
  e2e:
    runs-on: ubuntu-latest
    environment: e2e

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Dataverse Design System
        working-directory: packages/design-system
        run: npm run build

      - name: Create and populate .env file
        env:
          DATAVERSE_BACKEND_URL: ${{ secrets.DATAVERSE_BACKEND_URL }}
        run: |
          touch .env
          echo VITE_DATAVERSE_BACKEND_URL="$DATAVERSE_BACKEND_URL" >> .env
        shell: bash

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run preview
          wait-on: 'npx wait-on --timeout 60000 http://localhost:5173'
  component:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Dataverse Design System
        working-directory: packages/design-system
        run: npm run build

      - name: Cypress run Design System
        uses: cypress-io/github-action@v4
        with:
          working-directory: packages/design-system
          start: npm run preview
          component: true
          wait-on: 'npx wait-on --timeout 60000 http://localhost:4173'

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run preview
          component: true
          wait-on: 'npx wait-on --timeout 60000 http://localhost:5173'

      - name: Check coverage, merge coverage
        run: npm run test:coverage && npx lcov-result-merger '**/*/lcov.info' 'merged-coverage/merged-coverage.info'

      - name: Upload coverage report to Coveralls
        if: always()
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: merged-coverage/merged-coverage.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

  interaction-and-accessibility:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Dataverse Design System
        working-directory: packages/design-system
        run: npm run build

      - name: Build Storybook Design System
        working-directory: packages/design-system
        run: npm run build-storybook --quiet

      - name: Serve Storybook Design System and run tests
        working-directory: packages/design-system
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on http://127.0.0.1:6006 --l && npx test-storybook --url http://127.0.0.1:6006"

      - name: Build Storybook
        run: npm run build-storybook --quiet

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on http://127.0.0.1:6006 --l && npx test-storybook --url http://127.0.0.1:6006"
